using WhoCalledMe.Entities;

namespace WhoCalledMe.DbContexts
{
    public static partial class DbInitializer
    {
        private static Region[] _regions => new Region[]
            {
              //new Region { TimeZoneSpan = 0, Name = "Российская Федерация" },
                new Region { TimeZoneSpan = 0, Name = "Республика Адыгея" },
                new Region { TimeZoneSpan = 2, Name = "Республика Башкортостан" },
                new Region { TimeZoneSpan = 5, Name = "Республика Бурятия" },
                new Region { TimeZoneSpan = 4, Name = "Республика Алтай" },
                new Region { TimeZoneSpan = 0, Name = "Республика Дагестан" },
                new Region { TimeZoneSpan = 0, Name = "Республика Ингушетия" },
                new Region { TimeZoneSpan = 0, Name = "Кабардино-Балкарская Республика" },
                new Region { TimeZoneSpan = 0, Name = "Республика Калмыкия" },
                new Region { TimeZoneSpan = 0, Name = "Карачаево-Черкесская Республика" },
                new Region { TimeZoneSpan = 0, Name = "Республика Карелия" },
                new Region { TimeZoneSpan = 0, Name = "Республика Коми" },
                new Region { TimeZoneSpan = 0, Name = "Республика Марий Эл" },
                new Region { TimeZoneSpan = 0, Name = "Республика Мордовия" },
                new Region { TimeZoneSpan = 6, Name = "Республика Саха (Якутия)" },
                new Region { TimeZoneSpan = 0, Name = "Республика Северная Осетия - Алания" },
                new Region { TimeZoneSpan = 0, Name = "Республика Татарстан" },
                new Region { TimeZoneSpan = 4, Name = "Республика Тыва" },
                new Region { TimeZoneSpan = 1, Name = "Удмуртская Республика" },
                new Region { TimeZoneSpan = 4, Name = "Республика Хакасия" },
                new Region { TimeZoneSpan = 0, Name = "Чеченская Республика" },
                new Region { TimeZoneSpan = 0, Name = "Республика Чувашия" },
                new Region { TimeZoneSpan = 4, Name = "Алтайский край" },
                new Region { TimeZoneSpan = 0, Name = "Краснодарский край" },
                new Region { TimeZoneSpan = 4, Name = "Красноярский край" },
                new Region { TimeZoneSpan = 7, Name = "Приморский край" },
                new Region { TimeZoneSpan = 0, Name = "Ставропольский край" },
                new Region { TimeZoneSpan = 7, Name = "Хабаровский край" },
                new Region { TimeZoneSpan = 6, Name = "Амурская область" },
                new Region { TimeZoneSpan = 0, Name = "Архангельская область" },
                new Region { TimeZoneSpan = 1, Name = "Астраханская область" },
                new Region { TimeZoneSpan = 0, Name = "Белгородская область" },
                new Region { TimeZoneSpan = 0, Name = "Брянская область" },
                new Region { TimeZoneSpan = 0, Name = "Владимирская область" },
                new Region { TimeZoneSpan = 0, Name = "Волгоградская область" },
                new Region { TimeZoneSpan = 0, Name = "Вологодская область" },
                new Region { TimeZoneSpan = 0, Name = "Воронежская область" },
                new Region { TimeZoneSpan = 0, Name = "Ивановская область" },
                new Region { TimeZoneSpan = 5, Name = "Иркутская область" },
                new Region { TimeZoneSpan =-1, Name = "Калининградская область" },
                new Region { TimeZoneSpan = 0, Name = "Калужская область" },
                new Region { TimeZoneSpan = 9, Name = "Камчатская область" },
                new Region { TimeZoneSpan = 4, Name = "Кемеровская область" },
                new Region { TimeZoneSpan = 0, Name = "Кировская область" },
                new Region { TimeZoneSpan = 0, Name = "Костромская область" },
                new Region { TimeZoneSpan = 2, Name = "Курганская область" },
                new Region { TimeZoneSpan = 0, Name = "Курская область" },
                new Region { TimeZoneSpan = 0, Name = "Ленинградская область и г. Санкт-Петербург" },
                new Region { TimeZoneSpan = 0, Name = "Липецкая область" },
                new Region { TimeZoneSpan = 7, Name = "Магаданская область" },
                new Region { TimeZoneSpan = 0, Name = "Московская область и г. Москва" },
                new Region { TimeZoneSpan = 0, Name = "Мурманская область" },
                new Region { TimeZoneSpan = 0, Name = "Нижегородская область" },
                new Region { TimeZoneSpan = 0, Name = "Новгородская область" },
                new Region { TimeZoneSpan = 3, Name = "Новосибирская область" },
                new Region { TimeZoneSpan = 3, Name = "Омская область" },
                new Region { TimeZoneSpan = 2, Name = "Оренбургская область" },
                new Region { TimeZoneSpan = 0, Name = "Орловская область" },
                new Region { TimeZoneSpan = 0, Name = "Пензенская область" },
                new Region { TimeZoneSpan = 2, Name = "Пермская область" },
                new Region { TimeZoneSpan = 0, Name = "Псковская область" },
                new Region { TimeZoneSpan = 0, Name = "Ростовская область" },
                new Region { TimeZoneSpan = 0, Name = "Рязанская область" },
                new Region { TimeZoneSpan = 1, Name = "Самарская область" },
                new Region { TimeZoneSpan = 0, Name = "Саратовская область" },
                new Region { TimeZoneSpan = 8, Name = "Сахалинская область" },
                new Region { TimeZoneSpan = 2, Name = "Свердловская область" },
                new Region { TimeZoneSpan = 0, Name = "Смоленская область" },
                new Region { TimeZoneSpan = 0, Name = "Тамбовская область" },
                new Region { TimeZoneSpan = 0, Name = "Тверская область" },
                new Region { TimeZoneSpan = 3, Name = "Томская область" },
                new Region { TimeZoneSpan = 0, Name = "Тульская область" },
                new Region { TimeZoneSpan = 2, Name = "Тюменская область" },
                new Region { TimeZoneSpan = 1, Name = "Ульяновская область" },
                new Region { TimeZoneSpan = 2, Name = "Челябинская область" },
                new Region { TimeZoneSpan = 6, Name = "Забайкальский край" },
                new Region { TimeZoneSpan = 0, Name = "Ярославская область" },
                new Region { TimeZoneSpan = 0, Name = "г. Москва" },
                new Region { TimeZoneSpan = 0, Name = "г. Санкт-Петербург" },
                new Region { TimeZoneSpan = 7, Name = "Еврейская автономная область" },
                new Region { TimeZoneSpan = 5, Name = "Агинский Бурятский автономный округ" },
                new Region { TimeZoneSpan = 0, Name = "Коми-Пермяцкий автономный округ" },
                new Region { TimeZoneSpan = 9, Name = "Корякский автономный округ" },
                new Region { TimeZoneSpan = 0, Name = "Ненецкий автономный округ" },
                new Region { TimeZoneSpan = 4, Name = "Таймырский (Долгано-Ненецкий) автономный округ" },
                new Region { TimeZoneSpan = 5, Name = "Усть-Ордынский Бурятский автономный округ" },
                new Region { TimeZoneSpan = 2, Name = "Ханты-Мансийский автономный округ - Югра" },
                new Region { TimeZoneSpan = 9, Name = "Чукотский автономный округ" },
                new Region { TimeZoneSpan = 4, Name = "Эвенкийский автономный округ" },
                new Region { TimeZoneSpan = 2, Name = "Ямало-Ненецкий автономный округ" },
                new Region { TimeZoneSpan = 0, Name = "Республика Крым и г. Севастополь" },
                new Region { TimeZoneSpan = 3, Name = "г. Байконур" },
            };
    }
}
