using WhoCalledMe.Entities;

namespace WhoCalledMe.DbContexts
{
    public static partial class DbInitializer
    {
        private static Operator[] _operators => new Operator[]
            {
                //new Operator { ShortName = "", Name = "Стационарный телефон" },
                new Operator { ShortName = "Ростелеком", Name = "ОАО \"Ростелеком\"" },
                new Operator { ShortName = "Ростелеком", Name = "ПАО \"Ростелеком\"" },
                new Operator { ShortName = "МТС", Name = "ОАО \"Мобильные ТелеСистемы\"" },
                new Operator { ShortName = "МТС", Name = "ПАО \"Мобильные ТелеСистемы\"" },
                new Operator { ShortName = "Билайн", Name = "ОАО \"Вымпел-Коммуникации\"" },
                new Operator { ShortName = "Билайн", Name = "ПАО \"Вымпел-Коммуникации\"" },
                new Operator { ShortName = "МегаФон", Name = "ОАО \"МегаФон\"" },
                new Operator { ShortName = "МегаФон", Name = "ПАО \"МегаФон\"" },
                new Operator { ShortName = "Теле2", Name = "ООО \"Т2 Мобайл\"" },
                new Operator { ShortName = "Теле2", Name = "ОАО \"Теле2-Санкт-Петербург\"" },
                new Operator { ShortName = "Теле2", Name = "ЗАО \"РТ-Мобайл\"" },
                new Operator { ShortName = "Yota", Name = "ООО \"Скартел\"" },
                new Operator { ShortName = "СМАРТС", Name = "СМАРТС" },
                new Operator { ShortName = "СМАРТС", Name = "АО \"СМАРТС-Саранск\"" },
                new Operator { ShortName = "СМАРТС", Name = "Акционерное общество \"СМАРТС-Ульяновск\"" },
                new Operator { ShortName = "СМАРТС", Name = "АО \"СМАРТС-Йошкар-Ола\"" },
                new Operator { ShortName = "СМАРТС", Name = "АО \"СМАРТС-Пенза\"" },
                new Operator { ShortName = "СМАРТС", Name = "АО \"СМАРТС-Астрахань\"" },
                new Operator { ShortName = "СМАРТС", Name = "Акционерное общество \"СМАРТС-Саратов\"" },

                new Operator { ShortName = "", Name = "ОАО \"АСВТ\"" },
                new Operator { ShortName = "", Name = "ООО \"Глобал Телеком\"" },
                new Operator { ShortName = "", Name = "Акционерное общество \"ГЛОНАСС\"" },
                new Operator { ShortName = "", Name = "ООО \"Транснефть Телеком\"" },
                new Operator { ShortName = "", Name = "ОАО \"Межрегиональный ТранзитТелеком\"" },
                new Operator { ShortName = "", Name = "ООО \"Газпром телеком\"" },
                new Operator { ShortName = "", Name = "ООО \"ЕКАТЕРИНБУРГ-2000\"" },
                new Operator { ShortName = "", Name = "АО \"Мобиком Волга\"" },
                new Operator { ShortName = "", Name = "ЗАО \"Компания ТрансТелеКом\"" },
                new Operator { ShortName = "", Name = "ООО \"Эквант\"" },
                new Operator { ShortName = "", Name = "ЗАО \"РусСДО\"" },
                new Operator { ShortName = "", Name = "ОАО \"Основа Телеком\"" },
                new Operator { ShortName = "", Name = "ООО \"Твои мобильные технологии\"" },
                new Operator { ShortName = "", Name = "ОАО \"Московская городская телефонная сеть\"" },
                new Operator { ShortName = "", Name = "ЗАО \"Тюменьруском\"" },
                new Operator { ShortName = "", Name = "ООО \"Интернод\"" },
                new Operator { ShortName = "", Name = "ОАО \"Сотовая связь Башкортостана\"" },
                new Operator { ShortName = "", Name = "ООО \"Интеграл\"" },
                new Operator { ShortName = "", Name = "ООО \"СИМ ТЕЛЕКОМ\"" },
                new Operator { ShortName = "", Name = "ЗАО \"АКОС\"" },
                new Operator { ShortName = "", Name = "АО \"Глобалстар-Космические Телекоммуникации\"" },
                new Operator { ShortName = "", Name = "Кузбаск.сот. связь" },
                new Operator { ShortName = "", Name = "ТМ \"САТ\"" },
                new Operator { ShortName = "", Name = "ООО \"Спринт\"" },
                new Operator { ShortName = "", Name = "ООО \"Нэт Бай Нэт Холдинг\"" },
                new Operator { ShortName = "", Name = "государственное унитарное предприятие Севастополя \"СЕВАСТОПОЛЬ ТЕЛЕКОМ\"" },
                new Operator { ShortName = "", Name = "ООО \"Антарес\"" },
                new Operator { ShortName = "", Name = "ЗАО \"Мобильная сот.связь\"" },
                new Operator { ShortName = "", Name = "ОАО \"АПЕКС\"" },
                new Operator { ShortName = "", Name = "ЗАО \"СИБИНТЕРТЕЛЕКОМ\"" },
                new Operator { ShortName = "", Name = "ЗАО \"Ярославль-GSM\"" },
                new Operator { ShortName = "", Name = "ООО \"Иридиум Коммьюникешенс\"" },
                new Operator { ShortName = "", Name = "ООО \"ФЕБО Телеком\"" },
                new Operator { ShortName = "", Name = "ООО \"МАТРИКС телеком\"" },
                new Operator { ShortName = "", Name = "ООО \"Сонет\"" },
                new Operator { ShortName = "", Name = "ООО \"КТК ТЕЛЕКОМ\"" },
                new Operator { ShortName = "", Name = "ООО \"Арктур\"" },
                new Operator { ShortName = "", Name = "ОАО \"Арктик Регион Связь\"" },
                new Operator { ShortName = "", Name = "МТТ Инвест" },
                new Operator { ShortName = "", Name = "ОАО \"Региональный технический центр\"" },
                new Operator { ShortName = "", Name = "ЗАО \"Сотел- сот. связь Чувашии\"" },
                new Operator { ShortName = "", Name = "ОАО \"Облком\"" },
                new Operator { ShortName = "", Name = "Дагест сот связь" },
                new Operator { ShortName = "", Name = "ЗАО \"Джи Ти Эн Ти\"" },
                new Operator { ShortName = "", Name = "ЗАО \"ВЕСТ КОЛЛ ЛТД\"" },
                new Operator { ShortName = "", Name = "ООО \"Систематикс\"" },
                new Operator { ShortName = "", Name = "ООО \"Аврора Телеком\"" },
                new Operator { ShortName = "", Name = "ООО \"МиАТел\"" },
                new Operator { ShortName = "", Name = "Дальсвязь" },
                new Operator { ShortName = "", Name = "ОАО \"РТКомм.РУ\"" },
                new Operator { ShortName = "", Name = "ОАО \"Тывасвязьинформ\"" },
                new Operator { ShortName = "", Name = "ЗАО \"Вайнах Телеком\"" },
                new Operator { ShortName = "", Name = "ЗАО \"МИТ-ТЕЛ\"" },
                new Operator { ShortName = "", Name = "Северо-вост. Телеком" },
                new Operator { ShortName = "", Name = "Акционерное общество \"КОМСТАР ХМАО\"" },
                new Operator { ShortName = "", Name = "ЗАО \"Кабардино-Балкарская сотовая связь\"" },
                new Operator { ShortName = "", Name = "ЗАО \"Горно-Алтайская Сотовая Связь\"" },
                new Operator { ShortName = "", Name = "ОАО \"Северо-восточные Телекоммуникации\"" },
                new Operator { ShortName = "", Name = "Курганский Сотовый Телефон" },
                new Operator { ShortName = "", Name = "ММС Ингушетии" },
                new Operator { ShortName = "", Name = "Закрытое акционерное общество \"Финансовая Компания Императив\"" },
                new Operator { ShortName = "", Name = "ООО \"ЭСОТЕЛ-Рустелком\"" },
                new Operator { ShortName = "", Name = "ЗАО \"ДОЗОР-ТЕЛЕПОРТ\"" },
                new Operator { ShortName = "", Name = "ООО \"Открытая мобильная система\"" },
                new Operator { ShortName = "", Name = "ООО \"Спутниковые Мобильные Технологии\"" },
                new Operator { ShortName = "", Name = "ФГУП \"Морсвязьспутник\"" },
                new Operator { ShortName = "", Name = "ЗАО \"РадиоТел\"" },
                new Operator { ShortName = "", Name = "ЗАО \"Информационные транковые системы\"" },
                new Operator { ShortName = "", Name = "ООО \"Радиоимпульс\"" },
                new Operator { ShortName = "", Name = "МАГ" },
                new Operator { ShortName = "", Name = "ОАО \"Сургутнефтегаз\"" },
                new Operator { ShortName = "", Name = "ООО \"Метро-пэй\"" },
                new Operator { ShortName = "", Name = "ПАО \"Центральный телеграф\"" },
                new Operator { ShortName = "", Name = "ООО \"7к\"" },
                new Operator { ShortName = "", Name = "ООО \"Айконнект\"" },
                new Operator { ShortName = "", Name = "ООО \"Астрахань-Телеком\"" },
                new Operator { ShortName = "", Name = "ООО \"СервисПартнер\"" },
                new Operator { ShortName = "", Name = "ООО \"Интерком Технолоджи\"" },
                new Operator { ShortName = "", Name = "ООО \"Галс-Телеком\"" },
                new Operator { ShortName = "", Name = "ООО \"Телеком-Сервис\"" },
                new Operator { ShortName = "", Name = "ООО \"Центр 2М\"" },
                new Operator { ShortName = "", Name = "ООО \"Линк-Мастер\"" },
                new Operator { ShortName = "", Name = "ОАО \"Деловая Сеть - Иркутск\"" },
                new Operator { ShortName = "", Name = "ЗАО \"Интерсвязь-2\"" },
                new Operator { ShortName = "", Name = "ЗАО \"Экспресс ТелеКом\"" },
                new Operator { ShortName = "", Name = "ЗАО \"КантриКом\"" },
                new Operator { ShortName = "", Name = "С-Петербургский ММТ" },
                new Operator { ShortName = "", Name = "ЗАО \"МТУ-ИНФОРМ\"" },
                new Operator { ShortName = "", Name = "ООО \"Смолтелеком\"" },
                new Operator { ShortName = "", Name = "ООО \"Компьютерная скорая помощь\"" },
                new Operator { ShortName = "", Name = "ООО \"Фонеком\"" },
                new Operator { ShortName = "", Name = "ООО \"Элемтэ-Инвест\"" },
                new Operator { ShortName = "", Name = "ООО \"ИНТЕРТЕЛЕКОМ\"" },
                new Operator { ShortName = "", Name = "ГУП РК \"Крымтелеком\"" },
                new Operator { ShortName = "", Name = "ООО \"К-телеком\"" },
                new Operator { ShortName = "", Name = "ОАО \"МУРМАНСКИЙ ТРАЛОВЫЙ ФЛОТ\"" },
            };
    }
}
